cubes = [num**3 for num in range(0, 11)]
print(cubes)
print("***************")
print(cubes[2:6])
print("***************")
print(cubes)
print("***************")
print(cubes[3:])
print("***************")
print(cubes[:3])
print("***************")
print(cubes[-1])
print("***************")
print(cubes[-3:])
